name: Build and Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: ko
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'
      - uses: actions/checkout@v3
      - uses: ko-build/setup-ko@v0.7

      - run: |
          ko build --base-import-paths ./cmd/wn-smartmeter-influx/
